### ISSUE TITLE
pokemon names translations

### ISSUE THREAD

**Issue by thomasleveil** [iGio90/PokeMesh_Translations#14]
is there a way to translate pokemon names ?

[pokemon-names-fr.txt](https://github.com/iGio90/PokeMesh_Translations/files/416501/pokemon-names-fr.txt)

**Comment by iGio90** [comment]
Yes!! i can add them a separate resources! i din't know they have different names!

**Comment by LionisIAm** [comment]
I dont think its a good idea to change original names. As for me, its sounds quite better on English even any other transliteration.

**Comment by Tashla** [comment]
As far as that may be true, thus far I've met three people that were from a different country and they came to visit, and I clearly ran into a barrier as to where they didn't know half the time about which Pokémon I was talking (using the English names) but they were using the German language and thus the German names.

Now this may, or may not, contribute to this suggestion, as it'd most likely not have any value for me nor that person (as the barrier would still be present in PoGO), but it would only be applicable to speech, and only in reading for the individual. So he may have a profit from it to know exactly which Pokémon is nearby from just a notification instead of having to look at the icon ;)

**Comment by iGio90** [comment]
Does PokemonGO have localized Pokémon names? I think the better way, it's to follow their way. So that, if they are using localized name we are going for localized too!

**Comment by Tashla** [comment]
PokémonGO actually has localized character names, which are based on the device language. So if it's set to for example French or German it would actually use those names instead of the default English nameset.

**Comment by LionisIAm** [comment]
Got it. 
Didnt know about it bcs in Russian speaking area we are even havent official app yet ;D

**Comment by iGio90** [comment]
Anyway, i can set it to optional on settings to use original or localized names!

**Comment by Tashla** [comment]
That would be ideal! So people can choose whether to use their localized names or not :+1: Should look into something similiar for the app-language (like selectable language, which defaults to device language)?

**Comment by iGio90** [comment]
No, pokemon data are loaded thourgh an in-app json with single pokemon details so it would be easy to set them localized/unlocalized. Im preparing a new res file pokemon.xml with the pokemon names. Should be up in 10 min

**Comment by iGio90** [comment]
https://github.com/iGio90/PokeMesh_Translations/commit/97dc0acc6db616ebe9551d6910ef7f97a30fef36

closing the issue :)
